# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: detect-aws-credentials
    -   id: check-added-large-files
        args: ['--maxkb=1000']
-   repo: local
    hooks:
    -   id: alexa_skill_id_pygrep_check_git_hook
        name: Check that an amazon skill is not committed (ask-resources.json, ask-states.json, serverless.yml)
        entry: 'amzn1\.ask\.skill\..*'
        language: pygrep
    -   id: lambda_arn_pygrep_check_git_hook
        name: Check that an amazon skill's lambda arn is not committed (skill.json)
        entry: 'arn:aws:lambda:{9}:.*:function:.*'
        language: pygrep